### ISSUE TITLE
Soporte para varios tipos de bot

### ISSUE THREAD

**Issue by m4grio** [carlosherrera/cdmxbot#2]
Hay una iniciativa y un esfuerzo de reportar/banear/marcar noticias, tuits y links como falsos cuando ya haya sido totalmente veritifcado su falsedad.

Si hacemos que este proyecto pueda ejecutar al mismo tiempo varios tipos de bots, podemos tener diferentes funcionalidades cubiertas ayudando a la gente de diversas maneras.

Una idea es estar supervisando los hashtags `#sismo`, `#fuerzamexico` `#sismomexico2017` y si se encuentran links o RTs a cosas que ya sabemos son falsas, dar reply avisando que están compartiendo información falsa y pedir fav o RT en el texto del tuit para incrementar la visibilidad.

**Comment by fmicalizzi** [comment]
Podemos integrar a la búsqueda o filtro esta repo https://github.com/Garyi/Filtro-Informaci-n-Valiosa-Terremoto-Twitter

**Comment by carlosherrera** [comment]
Sólo hay que revisar bien la Streaming API de Twitter, porque entiendo que tiene límites en cuanto a los términos de búsqueda que se pueden usar.
